### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jghazarian** [Banbury/io_image_as_mesh#1]
This project looks really cool, but I'm having loading the plugin. After importing, when I try to enable it I get this error:

> Traceback (most recent call last):
>   File "/Applications/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/addon_utils.py", line 330, in enable
>     mod = __import__(module_name)
>   File "/Users/jonathan/Library/Application Support/Blender/2.78/scripts/addons/io_image_as_mesh-master/__init__.py", line 8, in <module>
>     from io_image_as_mesh.image_as_mesh import create_mesh_from_image
> ImportError: No module named 'io_image_as_mesh'

I tried this using Blender 2.78. Do you have any idea why I might have this problem?

**Comment by Banbury** [comment]
The plugin needs to be in a folder named 'io_image_as_mesh'.

You have it in a folder called 'io_image_as_mesh-master'. The folder name is also the module name.

**Comment by jghazarian** [comment]
That did it, thanks.

**Comment by Banbury** [comment]
I've changed the documentation accordingly.
