### ISSUE TITLE
2.79 support?

### ISSUE THREAD

**Issue by KatPurpy** [Banbury/io_image_as_mesh#2]
Hello! I want to ask you to add blender 2.79 support please :з

**Comment by Eymux** [comment]
This should work with 2.79. Do you have a specific problem?

**Comment by KatPurpy** [comment]
i can't see where it adds new buttons

**Comment by KatPurpy** [comment]
oh nvm just read documentation

also i had "import" problem but it was fixed by looking into the first issue

sorry for stupid questions and disturbing. have a nice day!
