### ISSUE TITLE
Can use in Blender 3.5.1, but is need little change

### ISSUE THREAD

**Issue by RonGeer** [Banbury/io_image_as_mesh#3]
In the "IO_IMAGES_AS_MESH" folder, "__init__.py", line 31: filename_ext: ".png", comment this line (#filename_ext: ".png"), which will work in Blender3.5.1
![image](https://github.com/Banbury/io_image_as_mesh/assets/30851164/e5f91237-f0c6-41bc-9bad-c31330994a68)

**Comment by Banbury** [comment]
Thanks for reporting this. I'll fix it as soon as I can.
